export { ChampagneSectionRenderer } from "./ChampagneSectionRenderer";
export { getSectionStack, type SectionRegistryEntry } from "./SectionRegistry";
export { resolveSectionComponent, SectionRegistry } from "./registry";
export type { SectionComponent, SectionComponentProps, SectionComponentRegistry, SectionComponentMap } from "./types";
export { computeFxProps, type FxProps } from "./fx";
export { Section_TextBlock } from "./Section_TextBlock";
export { Section_MediaBlock } from "./Section_MediaBlock";
export { Section_FeatureList } from "./Section_FeatureList";
export { Section_TreatmentOverviewRich } from "./Section_TreatmentOverviewRich";
export { Section_TreatmentMediaFeature } from "./Section_TreatmentMediaFeature";
export { Section_TreatmentToolsTrio } from "./Section_TreatmentToolsTrio";
export { Section_TreatmentRoutingCards } from "./Section_TreatmentRoutingCards";
export { Section_ClinicianInsight } from "./Section_ClinicianInsight";
export { Section_PatientStoriesRail } from "./Section_PatientStoriesRail";
export { Section_FAQ } from "./Section_FAQ";
export { Section_TreatmentClosingCTA } from "./Section_TreatmentClosingCTA";
export { Section_GoogleReviews } from "./Section_GoogleReviews";
