export {
  champagneMachineManifest,
  champagneManifestRegistry,
  champagneManifestStatus,
  champagneManifestsReady,
  champagneMediaDeckManifests,
  champagnePageTypeDefaults,
  champagneSectionFxDefaults,
  champagneSectionPrmDefaults,
  champagneSectionLayouts,
  champagneSectionLibrary,
  champagneStylesManifest,
  getRouteIdFromSlug,
  getPageManifestBySlug,
  getHeroPresetForPage,
  getSectionStackForPage,
  getMainNavItems,
  type ChampagneCTA,
  type ChampagnePageCTAConfig,
  type ChampagneMachineManifest,
  type ChampagneManifestRegistry,
  type ChampagneManifestStatus,
  type ChampagneMediaDeckManifest,
  type ChampagnePageManifest,
  type ChampagnePageSection,
  type ChampagnePageTypeDefault,
  type ChampagnePageTypeDefaults,
  type ChampagneSectionFxDefaultsManifest,
  type ChampagneSectionFxDefaultsEntry,
  type ChampagneSectionLayout,
  type ChampagneSectionLayoutSection,
  type ChampagneSectionLibrary,
  type ChampagneSectionLibraryEntry,
  type ChampagneSectionPrmDefaultsManifest,
  type ChampagneSectionPrmDefaultsEntry,
  type ChampagneJourneyManifest,
  type ChampagneJourneyState,
  type ChampagneJourneyStep,
  type ChampagneJourneyTransition,
  type ChampagneJourneyTransitionConditions,
  type ChampagneStylesManifest,
  type NavItem,
} from "./core";

export {
  getAllPages,
  getCTASlotsForPage,
  getHeroManifest,
  getPageManifest,
  getSectionManifest,
  getSectionCTAReferences,
  getSectionStyle,
  getSectionManifestSchema,
  getSectionLayoutManifest,
  getSectionLayouts,
  getSectionLayoutSections,
  getSectionLibrary,
  getPageTypeDefaults,
  getSectionFxDefaults,
  getSectionPrmDefaults,
  getJourneys,
  getJourneyManifest,
  getMediaDecks,
  getMediaDeck,
  getTreatmentManifest,
  getTreatmentAnswerSurface,
  resolveTreatmentPathAlias,
  getTreatmentPages,
  getCTAIntentConfigForRoute,
  getTreatmentJourneyForRoute,
  getCTAIntentLabels,
  validateSectionLayoutManifest,
  type ChampagneHeroManifest,
  type ChampagneCTASlots,
  type ChampagneSectionManifest,
  type ChampagneTreatmentPage,
  type ChampagneCTAIntentConfig,
} from "./helpers";
export {
  TREATMENT_ANSWER_SURFACE_REQUIRED_SECTION_IDS,
  validateTreatmentAnswerSurface,
  type TreatmentAnswerSurface,
  type TreatmentAnswerSurfaceFaq,
  type TreatmentAnswerSurfaceLink,
  type TreatmentAnswerSurfaceSection,
  type TreatmentAnswerSurfaceSectionId,
  type TreatmentAnswerSurfaceStatus,
  type TreatmentAnswerSurfaceValidationResult,
} from "./answerSurface";
export { useValidatedManifest } from "./useValidatedManifest";
export type { ChampagneManifest, ChampagneSectionEntry } from "./types";
