name: SBOM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 10 * * 1"

permissions:
  contents: read

jobs:
  sbom:
    name: Generate SBOM (CycloneDX)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: sbom.cyclonedx.json
